# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x11your_package_name\"9\n\x11SimilarityRequest\x12\x11\n\tsentence1\x18\x01 \x01(\t\x12\x11\n\tsentence2\x18\x02 \x01(\t\"#\n\x12SimilarityResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x32m\n\tYourModel\x12`\n\x11\x43omputeSimilarity\x12$.your_package_name.SimilarityRequest\x1a%.your_package_name.SimilarityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMILARITYREQUEST']._serialized_start=34
  _globals['_SIMILARITYREQUEST']._serialized_end=91
  _globals['_SIMILARITYRESPONSE']._serialized_start=93
  _globals['_SIMILARITYRESPONSE']._serialized_end=128
  _globals['_YOURMODEL']._serialized_start=130
  _globals['_YOURMODEL']._serialized_end=239
# @@protoc_insertion_point(module_scope)
